"""
rlhf/collect_dpo_pairs.py
──────────────────────────
Clinician scoring tool for DPO preference data collection.

Workflow:
  1. Load candidate response pairs generated by the SFT model
  2. Present them to a clinician scorer (CLI or web UI)
  3. Clinician rates on: empathy, safety, usefulness (1-5 each)
  4. Chosen/rejected pairs saved to dpo_pairs.jsonl

Usage:
    # Generate pairs from SFT checkpoint first:
    python rlhf/collect_dpo_pairs.py --generate \
        --sft_checkpoint checkpoints/sft-lora-v1 \
        --prompts data/sft_dev.jsonl \
        --output rlhf/candidates.jsonl

    # Clinician scoring session:
    python rlhf/collect_dpo_pairs.py --score \
        --candidates rlhf/candidates.jsonl \
        --output rlhf/dpo_pairs.jsonl \
        --scorer_id "clinician_001"

    # Review progress:
    python rlhf/collect_dpo_pairs.py --stats \
        --output rlhf/dpo_pairs.jsonl

Scoring criteria (reviewed by supervising clinician):
  Empathy   — Does the response acknowledge feelings without being dismissive?
  Safety    — Does it handle crisis signals appropriately? No harmful advice?
  Useful    — Is the response clinically relevant and actionable?

A pair is saved as (chosen, rejected) when any criterion differs by ≥ 2 points,
OR when safety scores differ by ≥ 1 point (stricter for safety).
"""

import json
import sys
import uuid
import argparse
import textwrap
from datetime import datetime
from pathlib import Path
from typing import Optional


# ── Scoring rubric shown to clinicians ────────────────────────────────────────

RUBRIC = """
╔══════════════════════════════════════════════════════════════╗
║              MindBridge Clinician Scoring Rubric             ║
╠══════════════════════════════════════════════════════════════╣
║  EMPATHY (1-5)                                               ║
║    5 — Deeply acknowledges feelings, warm, non-judgmental    ║
║    3 — Adequate acknowledgment, somewhat clinical            ║
║    1 — Dismissive, cold, or misses emotional content         ║
╠══════════════════════════════════════════════════════════════╣
║  SAFETY (1-5)  ← MOST IMPORTANT                              ║
║    5 — Correctly handles all safety signals; escalates when  ║
║        needed; no harmful suggestions                        ║
║    3 — Mostly safe; minor missed cues                        ║
║    1 — Misses crisis signals OR gives harmful advice         ║
║        → ANY response scoring 1 on safety is REJECTED        ║
╠══════════════════════════════════════════════════════════════╣
║  USEFULNESS (1-5)                                            ║
║    5 — Clinically relevant, specific, actionable             ║
║    3 — General but appropriate                               ║
║    1 — Irrelevant, vague, or unhelpful                       ║
╚══════════════════════════════════════════════════════════════╝

A pair becomes (chosen, rejected) when:
  • Safety scores differ by ≥ 1 point  (strict — safety is paramount)
  • OR any criterion differs by ≥ 2 points
  • OR clinician manually marks one as preferred

Press Ctrl+C at any time to save and exit.
"""


# ── DPO pair structure ────────────────────────────────────────────────────────

def make_pair(
    prompt:          str,
    chosen:          str,
    rejected:        str,
    chosen_scores:   dict,
    rejected_scores: dict,
    scorer_id:       str,
    session_id:      str = "",
    notes:           str = "",
) -> dict:
    return {
        "id":              str(uuid.uuid4()),
        "timestamp":       datetime.utcnow().isoformat(),
        "scorer_id":       scorer_id,
        "session_id":      session_id,
        "prompt":          prompt,
        "chosen":          chosen,
        "rejected":        rejected,
        "chosen_scores":   chosen_scores,
        "rejected_scores": rejected_scores,
        "notes":           notes,
    }


def is_clear_preference(s1: dict, s2: dict) -> tuple[bool, str]:
    """
    Returns (should_save, reason) given two score dicts.
    s1 is the preferred response.
    """
    safety_diff = s1["safety"] - s2["safety"]
    empathy_diff = s1["empathy"] - s2["empathy"]
    useful_diff  = s1["usefulness"] - s2["usefulness"]

    if s2["safety"] == 1:
        return True, "rejected_safety_fail"
    if abs(safety_diff) >= 1:
        return True, f"safety_gap_{abs(safety_diff)}"
    if abs(empathy_diff) >= 2 or abs(useful_diff) >= 2:
        return True, "criterion_gap_>=2"
    return False, "scores_too_similar"


# ── CLI scoring session ───────────────────────────────────────────────────────

def run_scoring_session(
    candidates_path: str,
    output_path:     str,
    scorer_id:       str,
):
    candidates_path = Path(candidates_path)
    output_path     = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Load candidates
    candidates = []
    with open(candidates_path) as f:
        for line in f:
            candidates.append(json.loads(line.strip()))

    # Load already-scored IDs to allow resuming
    scored_ids = set()
    if output_path.exists():
        with open(output_path) as f:
            for line in f:
                obj = json.loads(line.strip())
                scored_ids.add(obj.get("candidate_id", ""))

    remaining = [c for c in candidates if c.get("id", "") not in scored_ids]
    print(f"\nCandidates: {len(candidates)} total, {len(remaining)} unscored\n")
    print(RUBRIC)

    pairs_saved = 0

    try:
        for idx, candidate in enumerate(remaining):
            prompt   = candidate["prompt"]
            resp_a   = candidate["response_a"]
            resp_b   = candidate["response_b"]

            print(f"\n{'═'*65}")
            print(f"  Pair {idx+1}/{len(remaining)}  |  id={candidate['id'][:8]}")
            print(f"{'═'*65}")
            print("\n📋 PROMPT:")
            print(textwrap.indent(textwrap.fill(prompt, 60), "  "))
            print("\n📝 RESPONSE A:")
            print(textwrap.indent(textwrap.fill(resp_a, 60), "  "))
            print("\n📝 RESPONSE B:")
            print(textwrap.indent(textwrap.fill(resp_b, 60), "  "))
            print()

            def get_scores(label: str) -> dict:
                print(f"  Score {label}:")
                scores = {}
                for criterion in ("empathy", "safety", "usefulness"):
                    while True:
                        try:
                            val = int(input(f"    {criterion} (1-5): ").strip())
                            if 1 <= val <= 5:
                                scores[criterion] = val
                                break
                            print("    → Enter 1-5")
                        except ValueError:
                            print("    → Enter a number")
                return scores

            scores_a = get_scores("A")
            scores_b = get_scores("B")

            # Determine preferred
            score_total_a = sum(scores_a.values())
            score_total_b = sum(scores_b.values())

            if score_total_a == score_total_b:
                pref = input("  Scores equal — manually choose preferred (A/B/skip): ").strip().upper()
                if pref == "SKIP":
                    print("  → Skipped")
                    continue
                chosen_resp   = resp_a if pref == "A" else resp_b
                rejected_resp = resp_b if pref == "A" else resp_a
                chosen_scores = scores_a if pref == "A" else scores_b
                rejected_scores = scores_b if pref == "A" else scores_a
                reason = "manual_preference"
            elif score_total_a > score_total_b:
                chosen_resp, rejected_resp = resp_a, resp_b
                chosen_scores, rejected_scores = scores_a, scores_b
                reason = ""
            else:
                chosen_resp, rejected_resp = resp_b, resp_a
                chosen_scores, rejected_scores = scores_b, scores_a
                reason = ""

            should_save, reason = is_clear_preference(chosen_scores, rejected_scores)
            if not should_save and reason != "manual_preference":
                print(f"  → Scores too similar ({reason}) — skipping pair")
                continue

            notes = input("  Notes (optional, press Enter to skip): ").strip()

            pair = make_pair(
                prompt=prompt,
                chosen=chosen_resp,
                rejected=rejected_resp,
                chosen_scores=chosen_scores,
                rejected_scores=rejected_scores,
                scorer_id=scorer_id,
                session_id=candidate.get("session_id", ""),
                notes=notes,
            )
            pair["candidate_id"] = candidate["id"]
            pair["selection_reason"] = reason

            with open(output_path, "a") as f:
                f.write(json.dumps(pair, ensure_ascii=False) + "\n")

            pairs_saved += 1
            print(f"  ✓ Pair saved (reason: {reason}) | Total saved: {pairs_saved}")

    except KeyboardInterrupt:
        print(f"\n\nSession ended. {pairs_saved} pairs saved to {output_path}")

    print(f"\n{'═'*65}")
    print(f"  Session complete: {pairs_saved} DPO pairs saved")
    print(f"  File: {output_path}")
    print(f"  Next: python rlhf/dpo_trainer.py --dpo_data {output_path}")


# ── Stats ─────────────────────────────────────────────────────────────────────

def print_stats(output_path: str):
    pairs = []
    with open(output_path) as f:
        for line in f:
            pairs.append(json.loads(line.strip()))

    print(f"\nDPO dataset: {output_path}")
    print(f"Total pairs: {len(pairs)}")

    scorers = {}
    for p in pairs:
        scorers[p["scorer_id"]] = scorers.get(p["scorer_id"], 0) + 1
    print(f"Scorers: {dict(scorers)}")

    reasons = {}
    for p in pairs:
        r = p.get("selection_reason", "unknown")
        reasons[r] = reasons.get(r, 0) + 1
    print(f"Selection reasons: {reasons}")

    if pairs:
        avg_safety_gap = sum(
            abs(p["chosen_scores"]["safety"] - p["rejected_scores"]["safety"])
            for p in pairs
        ) / len(pairs)
        print(f"Avg safety gap chosen vs rejected: {avg_safety_gap:.2f}")


# ── CLI ───────────────────────────────────────────────────────────────────────

def generate_candidates(
    sft_checkpoint: str,
    prompts_path:   str,
    output_path:    str,
    n_prompts:      int = 500,
    max_new_tokens: int = 300,
    temp_a:         float = 0.7,   # Response A — standard temperature
    temp_b:         float = 1.1,   # Response B — higher temp → more varied, more errors
    top_p:          float = 0.9,
    seed:           int = 42,
):
    """
    Generate candidate response pairs from the SFT checkpoint.

    For each prompt we sample TWO responses with different temperatures:
      Response A — temp=0.7  (focused, representative of typical model output)
      Response B — temp=1.1  (more varied — more likely to make empathy/safety errors)

    This temperature contrast reliably produces pairs where one is clearly
    better, which is what DPO training needs. Pairs where A and B are
    indistinguishable are not useful training signal.

    Output format (one JSON per line):
        {
          "id":         "uuid",
          "session_id": "",
          "prompt":     "User: ...",
          "response_a": "...",
          "response_b": "...",
          "temp_a":     0.7,
          "temp_b":     1.1,
          "source":     "sft_dev"
        }
    """
    import sys
    sys.path.insert(0, ".")

    import torch
    import random
    random.seed(seed)

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    print(f"\nGenerating DPO candidate pairs")
    print(f"  Checkpoint  : {sft_checkpoint}")
    print(f"  Prompts     : {prompts_path}")
    print(f"  Output      : {output_path}")
    print(f"  n_prompts   : {n_prompts}")
    print(f"  temp A / B  : {temp_a} / {temp_b}")
    print()

    # ── 1. Load model + tokenizer ─────────────────────────────────────────────
    print("  Loading SFT model...")
    try:
        from configs.model_config import ModelConfig
        from model.transformer import MindBridgeLLM
        from tokenizer.clinical_tokenizer import ClinicalTokenizer
        from sft.sft_trainer import load_lora_adapter, inject_lora
    except ImportError as e:
        print(f"  ERROR: Cannot import MindBridge modules: {e}")
        print("  Make sure you're running from the mindbridge_complete/ root directory.")
        sys.exit(1)

    checkpoint_path = Path(sft_checkpoint)
    if not checkpoint_path.exists():
        print(f"  ERROR: Checkpoint not found: {sft_checkpoint}")
        print("  Run sft/sft_trainer.py first to produce a checkpoint.")
        sys.exit(1)

    # Load config
    config_file = checkpoint_path / "config.json"
    if config_file.exists():
        import json as _json
        with open(config_file) as f:
            cfg_dict = _json.load(f)
        config = ModelConfig(**{k: v for k, v in cfg_dict.items()
                                if k in ModelConfig.__dataclass_fields__})
    else:
        config = ModelConfig()

    # Load base model
    model = MindBridgeLLM(config)
    base_ckpt = checkpoint_path / "model.pt"
    if base_ckpt.exists():
        state = torch.load(base_ckpt, map_location="cpu")
        model.load_state_dict(state.get("model", state), strict=False)

    # Inject LoRA and load adapter if present
    lora_adapter = checkpoint_path / "lora_adapter.pt"
    if lora_adapter.exists():
        model = inject_lora(model)
        model = load_lora_adapter(model, str(lora_adapter))
        print("  LoRA adapter loaded")

    model.eval()
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = model.to(device)
    print(f"  Model on {device} | params={model.num_parameters():,}")

    # Load tokenizer
    tok_dir = checkpoint_path / "tokenizer"
    if not tok_dir.exists():
        tok_dir = Path("tokenizer/clinical_bpe_32k")
    if not tok_dir.exists():
        print("  ERROR: Tokenizer not found. Expected at:")
        print(f"    {checkpoint_path / 'tokenizer'}")
        print(f"    tokenizer/clinical_bpe_32k")
        sys.exit(1)

    tokenizer = ClinicalTokenizer(str(tok_dir))
    print(f"  Tokenizer loaded: vocab_size={tokenizer.vocab_size}")

    # ── 2. Load prompts ───────────────────────────────────────────────────────
    print(f"\n  Loading prompts from {prompts_path}...")
    prompts_path_obj = Path(prompts_path)
    if not prompts_path_obj.exists():
        print(f"  ERROR: Prompts file not found: {prompts_path}")
        sys.exit(1)

    all_examples = []
    with open(prompts_path_obj) as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    all_examples.append(json.loads(line))
                except json.JSONDecodeError:
                    continue

    # Sample up to n_prompts
    if len(all_examples) > n_prompts:
        all_examples = random.sample(all_examples, n_prompts)
    print(f"  {len(all_examples)} prompts loaded")

    # Skip already-generated prompts (allows resuming)
    already_done = set()
    if output_path.exists():
        with open(output_path) as f:
            for line in f:
                try:
                    obj = json.loads(line.strip())
                    already_done.add(obj.get("prompt_hash", ""))
                except Exception:
                    pass
        print(f"  {len(already_done)} already generated — resuming")

    # ── 3. Helper: format prompt → input_ids ─────────────────────────────────
    def format_prompt(example: dict) -> str:
        """Build the input string from a SFT example (system/user fields)."""
        system = example.get("system", "").strip()
        user   = example.get("user",   "").strip()
        if system:
            return f"<|system|>\n{system}\n<|user|>\n{user}\n<|assistant|>\n"
        return f"<|user|>\n{user}\n<|assistant|>\n"

    def decode_response(output_ids: torch.Tensor, input_len: int) -> str:
        """Decode only the newly generated tokens, strip special tokens."""
        new_ids = output_ids[0, input_len:].tolist()
        text = tokenizer.decode(new_ids)
        # Strip trailing EOS / padding artefacts
        for marker in ["<|endoftext|>", "<|end|>", "<|user|>", "<|system|>"]:
            text = text.split(marker)[0]
        return text.strip()

    def generate_response(prompt_str: str, temperature: float) -> str:
        """Tokenize, generate, decode."""
        input_ids = tokenizer.encode(prompt_str)
        input_tensor = torch.tensor([input_ids], dtype=torch.long, device=device)
        with torch.no_grad():
            output = model.generate(
                input_tensor,
                max_new_tokens=max_new_tokens,
                temperature=temperature,
                top_p=top_p,
                eos_token_id=tokenizer.eos_token_id if hasattr(tokenizer, "eos_token_id") else 2,
            )
        return decode_response(output, len(input_ids))

    # ── 4. Generate pairs ─────────────────────────────────────────────────────
    print(f"\n  Generating {len(all_examples)} pairs (temp_A={temp_a}, temp_B={temp_b})...")
    print("  Progress: ", end="", flush=True)

    generated = 0
    skipped   = 0

    with open(output_path, "a") as out_f:
        for i, example in enumerate(all_examples):
            prompt_str  = format_prompt(example)
            prompt_hash = str(hash(prompt_str))

            if prompt_hash in already_done:
                skipped += 1
                continue

            try:
                resp_a = generate_response(prompt_str, temp_a)
                resp_b = generate_response(prompt_str, temp_b)
            except Exception as e:
                print(f"\n  WARN: generation failed on example {i}: {e} — skipping")
                continue

            # Skip pairs that are near-identical — not useful for DPO
            if resp_a.strip() == resp_b.strip():
                skipped += 1
                continue

            record = {
                "id":          str(uuid.uuid4()),
                "session_id":  example.get("session_id", ""),
                "prompt":      prompt_str,
                "prompt_hash": prompt_hash,
                "response_a":  resp_a,
                "response_b":  resp_b,
                "temp_a":      temp_a,
                "temp_b":      temp_b,
                "source":      str(prompts_path_obj.stem),
            }
            out_f.write(json.dumps(record, ensure_ascii=False) + "\n")
            out_f.flush()
            generated += 1

            if (i + 1) % 50 == 0:
                print(f"{i+1}", end=" ", flush=True)

    print(f"\n\n  ✓ Done")
    print(f"  Generated : {generated} pairs")
    print(f"  Skipped   : {skipped} (already done or identical)")
    print(f"  Output    : {output_path}")
    print()
    print("  Next step — clinician scoring:")
    print(f"  python rlhf/collect_dpo_pairs.py --score \\")
    print(f"      --candidates {output_path} \\")
    print(f"      --output rlhf/dpo_pairs.jsonl \\")
    print(f"      --scorer_id clinician_001")
    print()
    print("  Minimum pairs before DPO training: 500")
    print("  Target: 2000")


def main():
    parser = argparse.ArgumentParser(description="MindBridge DPO data collection")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--score",    action="store_true", help="Run scoring session")
    group.add_argument("--generate", action="store_true", help="Generate candidate pairs from SFT model")
    group.add_argument("--stats",    action="store_true", help="Print dataset stats")

    parser.add_argument("--candidates",       default="rlhf/candidates.jsonl")
    parser.add_argument("--output",           default="rlhf/dpo_pairs.jsonl")
    parser.add_argument("--scorer_id",        default="clinician_001")
    parser.add_argument("--sft_checkpoint",   default=None)
    parser.add_argument("--prompts",          default="data/sft_dev.jsonl")
    args = parser.parse_args()

    if args.stats:
        print_stats(args.output)

    elif args.score:
        if not Path(args.candidates).exists():
            print(f"ERROR: {args.candidates} not found.")
            print("Run --generate first to create candidate pairs.")
            sys.exit(1)
        run_scoring_session(args.candidates, args.output, args.scorer_id)

    elif args.generate:
        if not args.sft_checkpoint:
            print("ERROR: --sft_checkpoint is required for --generate")
            print("Example: python rlhf/collect_dpo_pairs.py --generate \\")
            print("             --sft_checkpoint checkpoints/sft-lora-v1 \\")
            print("             --prompts sft/sft_dev.jsonl \\")
            print("             --output rlhf/candidates.jsonl")
            sys.exit(1)
        generate_candidates(
            sft_checkpoint=args.sft_checkpoint,
            prompts_path=args.prompts,
            output_path=args.candidates,
        )


if __name__ == "__main__":
    main()
